# Generated by Django 5.1.2 on 2024-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('status', models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deregistered', 'Deregistered')], default='Active')),
                ('model_version', models.CharField(default=1.0, max_length=10)),
                ('trusted', models.BooleanField(default=True)),
            ],
        ),
    ]
