# Generated by Django 5.1.2 on 2024-12-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='trusted',
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deregistered', 'Deregistered')], default='Active', max_length=20),
        ),
    ]
