# Generated by Django 5.1.2 on 2024-12-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_remove_clientinfo_trusted_alter_clientinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='model_file',
            field=models.FileField(null=True, upload_to='client_models/'),
        ),
    ]
