# Generated by Django 5.1.2 on 2024-11-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=255)),
                ('port', models.IntegerField(max_length=10)),
                ('registered_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
