# Generated by Django 5.1.2 on 2024-11-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_clientinfo_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='username',
            field=models.CharField(default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.FloatField()),
                ('model_file', models.FileField(upload_to='modelfiles/')),
                ('model_summary', models.FileField(upload_to='summaryfiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='server_app.clientinfo')),
            ],
        ),
    ]
