# Generated by Django 5.1.2 on 2024-11-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_clientinfo_username_clientfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfile',
            name='version_number',
        ),
    ]
