# Generated by Django 5.1.2 on 2024-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=100)),
                ('X', models.PositiveIntegerField()),
                ('Y', models.PositiveIntegerField()),
                ('classification', models.IntegerField(choices=[(1, 'cancercell'), (0, 'normalcell')])),
            ],
        ),
    ]
