# Generated by Django 5.1.2 on 2024-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepaths',
            name='patient_id',
            field=models.IntegerField(default=-1),
        ),
    ]
